### ISSUE TITLE
Number of Entries

### ISSUE THREAD

**Issue by Niach** [HackerspaceBielefeld/plugin.video.streama#6]
Currently only the first 30 movies/series are shown in the list. It would be nice if the new Setting introduced in Streama 1.5.0 would be used, so each user can set how many entries he wants.

**Comment by marius-tu** [comment]
This can be solved by changing

`items = opener.open(streamaurl + '/dash/listShows.json')` and
`items = opener.open(streamaurl + '/dash/listMovies.json')`

(lines 75 and 83) to 

`items = opener.open(streamaurl + '/dash/listShows.json?max=' + maxval)` and
`items = opener.open(streamaurl + '/dash/listMovies.json?max=' + maxval)`

if you have created and imported a setting called 'maxval'. Nonetheless, this Plugin seems to have some Problems with Version 1.5.0, because I can't play any Video, although it is working in the Browser.

Edit: There was an error with the streama URL, now it's working again.

**Comment by bodems** [comment]
I added a setting option in 65f10e1d9150615604a8ec74c4f100310dcbe706. This isn't an ideal solution, but at least it works.

**Comment by Niach** [comment]
Thanks!
